// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfK2WgvgNptxzdvILlQPuCP6Mcl1iTlVE',
    appId: '1:602203538083:web:f29bd17a6e15169da43516',
    messagingSenderId: '602203538083',
    projectId: 'cmsc23-todo-app--caenriquez',
    authDomain: 'cmsc23-todo-app--caenriquez.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app--caenriquez.appspot.com',
    measurementId: 'G-FX24BE7TBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtPfTs7UsgmK5Dm7kF55SlVmJPSG6aoi8',
    appId: '1:602203538083:android:ba0cc6064fe99ca7a43516',
    messagingSenderId: '602203538083',
    projectId: 'cmsc23-todo-app--caenriquez',
    storageBucket: 'cmsc23-todo-app--caenriquez.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHF4fvfWbTFWOug81EsxiRJHNb-0OZG0I',
    appId: '1:602203538083:ios:853b2a3a649ac435a43516',
    messagingSenderId: '602203538083',
    projectId: 'cmsc23-todo-app--caenriquez',
    storageBucket: 'cmsc23-todo-app--caenriquez.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHF4fvfWbTFWOug81EsxiRJHNb-0OZG0I',
    appId: '1:602203538083:ios:853b2a3a649ac435a43516',
    messagingSenderId: '602203538083',
    projectId: 'cmsc23-todo-app--caenriquez',
    storageBucket: 'cmsc23-todo-app--caenriquez.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfK2WgvgNptxzdvILlQPuCP6Mcl1iTlVE',
    appId: '1:602203538083:web:dd2c0819910c1e3da43516',
    messagingSenderId: '602203538083',
    projectId: 'cmsc23-todo-app--caenriquez',
    authDomain: 'cmsc23-todo-app--caenriquez.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app--caenriquez.appspot.com',
    measurementId: 'G-SQN7VBLGYS',
  );

}